os: osx
osx_image: xcode11.2
rvm: system
sudo: true
language: ruby

env:
  jobs:
    - FORMULA_VERSION=
    - FORMULA_VERSION=--HEAD
jobs:
  fast_finish: true

homebrew:
  update: true

install:
  - brew update
  - brew --env
  - brew config

before_script:
  - mkdir -p $(brew --repo)/Library/Taps/hekmekk
  - ln -s $TRAVIS_BUILD_DIR $(brew --repo)/Library/Taps/hekmekk/homebrew-git-team

script:
  - brew tap hekmekk/git-team
  - brew install git-team $FORMULA_VERSION --verbose
  - brew audit git-team --strict
  - brew test git-team
  - git-team --version
